; PlatformIO Project Configuration File
; Sensor ATmega328P — Monitor de Energia
; Medição de tensão AC via ZMPT101B

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<main.cpp>

upload_speed = 115200

; Monitor serial (para debug)
monitor_speed = 9600
; Configurações de build
build_flags = 
    -DF_CPU=16000000L
    -DARDUINO_ARCH_AVR

[env:uno-energia]
extends = env:uno
build_src_filter = +<main_energia_rua.cpp>
